'use strict';
// Concise move formats per game (derived from games/<id>.js handleMove).
// Every move is sent as `data` of a game_move message. Seats are 0-based.
module.exports = {
  tictactoe: 'Move {cell} cell 0-8 (row-major). Ex: {"cell":4}. state.board[9] holds seat index or null.',
  gomoku: 'Move {row,col} 0-14. Ex: {"row":7,"col":7}.',
  connect4: 'Move {col} column 0-6. Ex: {"col":3}.',
  reversi: 'Move {row,col}, or {pass:true} when no legal move. Ex: {"row":2,"col":3}.',
  go9: 'Move {row,col} 0-8, or {pass:true}. Ex: {"row":4,"col":4}.',
  checkers: 'Move {from:[r,c],to:[r,c]} (check state for exact coordinate shape; continue multi-jumps with same piece). Use suggest_move for a legal one.',
  chess: 'Move {from,to,promote?} squares as in state (e.g. "e2","e4"); promote one of q/r/b/n. Ex: {"from":"e2","to":"e4"}.',
  chinesechess: 'Move {from,to} board coordinates as used in state.board (row/col). Use suggest_move for the exact shape.',
  battleship: 'Placing phase: {r,c,orientation:"h"|"v",size} ships in order of state SHIP sizes (size must equal the next ship size). Shooting phase: {r,c}. Ex: {"r":3,"c":4}.',
  twentyfour: 'Race game, no turns. Move {expression:"(3+5)*3"} using all 4 numbers once to make 24. When wait_for_turn returns reason round_end, call next_round (any player).',
  numberbomb: 'Move {guess:number} within the current range shown in state; avoid the bomb number.',
  sudoku: 'Move {type:"fill",row,col,val} (0-based, val 1-9). Race: everyone solves the same puzzle on their own board; a wrong fill costs a heart. {type:"hint"} spends one of 3 hints.',
  minesweeper: 'Move {action:"reveal"|"flag",row,col}. Ex: {"action":"reveal","row":3,"col":3}.',
  "2048": 'Move {dir} one of "up","down","left","right" (check state for accepted values).',
  snakebattle: 'Realtime. Move {direction} one of "up","down","left","right". Send occasionally; the server ticks.',
  suikabattle: 'Realtime canvas game; moves {type:"drop"} / {type:"merge",fruitType} / {type:"gameover"} are client-generated. Not practical for an agent.',
  sheeptile: 'Move {type:"pick",tileId} picks a free tile; powers: {type:"power_undo"}, {type:"power_shuffle"}, {type:"power_pop3"}.',
  flightchess: 'Move {action:"roll"} to roll the dice, then {action:"move",planeIndex:0-3} to move a plane (see state.diceValue / movable planes).',
  monopoly: 'Move {type:"roll"} | {type:"buy"} | {type:"skip_buy"} | {type:"build",spaceIndex?} | {type:"end_turn"}. Follow state phase.',
  uno: 'Play {cardId,chosenColor?} (chosenColor for wild: "red"|"yellow"|"green"|"blue"). Draw: {} with no cardId (see state). Call uno: {uno:true} with the play. Challenge +4: {challengeResponse:true|false}.',
  oldmaid: 'Move {cardIndex} index of the card to draw from the previous player\'s hand.',
  bigtwo: 'Move {cards:[cardId,...]} to play; {cards:[]} to pass. Card ids from your hand in state.',
  doudizhu: 'Bid: {call:true} / {pass:true}; rob: {rob:true} / {passRob:true}; play: {cards:[ids]} ; pass: {pass:true}; end: {action:"continue_vote",vote:"yes"|"no"} or {action:"next_round"}. Follow state.phase.',
  hearts: 'Pass phase: {cards:[3 ids]}; play: {card:cardId}. Follow state.phase.',
  texas: 'Move {action:"fold"|"check"|"call"|"raise"|"allin", amount?}. Ex: {"action":"raise","amount":40}.',
  "exploding-kittens": 'Play card {cardId,targetPlayer?}; draw: {draw:true}; after defusing give {position:n} (where to reinsert the bomb). Nope/favor responses: play {cardId} / see state.phase.',
  davinci: 'Phases: {placeIndex} to place a drawn joker, {revealIndex}, or guess {targetPlayer,tileIndex,guessNum|guessJoker:true}; after a correct guess {continueGuess:true} or {pass:true} to stop.',
  liarsbar: 'Play cards: {cardIds:[ids]} (1-3); call liar: {action:"liar"}; shoot when state.currentShooter is you: {action:"shoot"}. See state for exact action names via suggest_move.',
  rummikub: 'Play a new set: {tileIds:[...]}; add one tile to a table set: {tileIds:[id],targetSet:index}; rearrange the table: {action:"start_manipulate"} then {action:"submit",groups:[[tile,...],...]} (each tile is the full object {color,num,id[,wild]}, and groups must list EVERY table tile plus the hand tiles you play) or {action:"cancel"}; draw: {pass:true}; end turn after playing: {endTurn:true}. First meld must total 30+ from hand tiles.',
  "mahjong-sichuan": 'Moves by type: {type:"swap",tileIds:[3]} (swap phase), {type:"void",suit}, {type:"discard",tileId}, {type:"pung"|"kong"|"win"|"pass"} to react to a discard, {type:"selfkong"|"addkong",suit,num}, {type:"win"} (self-draw).',
  "mahjong-cantonese": 'Moves by type: {type:"discard",tileId}, {type:"win"}, {type:"selfkong"|"addkong"}, reactions {type:"pass"|"chow"|"pung"|"kong"|"win"} (chow may need tile choice - see state).',
  drawguess: 'Moves by type: {type:"choose_word",index}, {type:"stage_stroke",stroke:{pts:[[x,y],...],...}}, {type:"stage_guess",text}, {type:"submit",content}, {type:"vote_match",value:"match"|"drift"}, {type:"vote",stepIndex}. Follow state.phase.',
  truthdare: 'Move {action:"draw",kind:"truth"|"dare"|"random"}.',
  werewolf: 'Moves by {type}: chat {type:"chat",text}; night wolf/seer {type:"act"?,target:seat|-1}; witch {save:bool,poison:seat|-1}; sheriff {type:"run",run:bool}; vote {target:seat|-1}; hunter/badge {target}. Phase-driven; exact type names are in games/werewolf.js (state.phase, state.ask-like fields). Use suggest_move.',
  sanguo: 'Phase driven by state.ask (to === my seat). play: {type:"use",cardId,targets:[seats]} | {type:"skill",skill,cardIds,targets} | {type:"end"}; respond: {type:"use",cardId} or {type:"pass"}; discard: {type:"discard",cardIds}. Use suggest_move for legal shapes.',
};
